export const clothesSizes = [
  "xxs",
  "xs",
  "s",
  "m",
  "l",
  "xl",
  "xxl",
  "3xl",
  "4xl",
  "5xl",
];

export const shoesSizes = [
  "35",
  "35.5",
  "36",
  "36.5",
  "37",
  "37.5",
  "38",
  "38.5",
  "39",
  "39.5",
  "40",
  "40.5",
  "41",
  "41.5",
  "42",
  "42.5",
  "43",
  "43.5",
  "44",
  "44.5",
  "45",
  "45.5",
  "46",
  "46.5",
  "47",
  "47.5",
  "48",
  "48.5",
  "49",
  "49.5",
  "50",
];

const occasions = ["casual", "elegante", "serio", "festa"];
const materials = [
  //   "alpaca",
  //   "angora",
  //   "cammello",
  "cashmere",
  "lana",
  "lambswool",
  "mohair",
  "pelle",
  "seta",
  "cotone",
  "canapa",
  "juta",
  "lino",
  "flanella",
  //   "ramiè",
  //   "viscosa",
  //   "rayon",
  //   "acrilico",
  //   "elastan",
  //   "poliestere",
  //   "poliammide",
  //   "alcantara",
  //   "lurex",
  "gomma",
  //   "tencel",
  //   "modal",
  //   "polipropilene",
  //   "poliuretano",
  //   "lycra",
  "nylon",
  "gore-Tex",
  "microfibra",
  "pile",
  "stoffa",
  "chino",
  "jeans",
];

const genders = ["m", "f"];

const lengths = ["corto", "lungo", "normale"];

const types = ["basic", "stampato", "ricamato"];

const fits = ["skinny", "slim", "regular", "oversize", "baggy"];

const traits = ["vegan", "vintage", "handmade", "eco-friendly"];

const shirtCollars = [
  "italiano",
  "francese",
  "button down",
  "coreana",
  "cerimonia",
];

const sweaterCollars = ["girocollo", "dolcevita", "cardigan"];

export const macroCategories: any[] = [
  {
    macroCategory: "vestiti",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategories: ["caftani", "camicia", "maglina", "tubini", "lunghi"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "t-Shirt",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategories: [
      "maniche lunghe",
      "maniche corte",
      "mezze maniche",
      "senza maniche",
      "jeans",
    ],
    sizes: clothesSizes,
  },
  {
    macroCategory: "top",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: [
      "maniche lunghe",
      "maniche corte",
      "mezze maniche",
      "senza maniche",
    ],
    sizes: clothesSizes,
  },
  {
    macroCategory: "camicie",
    occasions: occasions, //TODO
    materials: materials, //TODO
    genders: genders,
    lengths: lengths, //TODO
    types: types, //TODO
    collars: shirtCollars, //TODO
    fits: fits,
    microCategory: ["basic", "hawaiana", "jeans"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "bluse",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: ["basic", "senza maniche", "trapezio"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "pantaloni",
    occasions: occasions,
    materials: materials,
    genders: genders,
    types: types,
    //non ha lenghts perche la lunghezza sarebbe la taglia
    fits: fits,
    microCategory: [
      "basic",
      "leggins",
      "cargo",
      "salopette",
      "tuta",
      "palazzo",
      "zampa d'elefante",
    ],
    sizes: clothesSizes,
  },
  {
    macroCategory: "jeans",
    occasions: occasions,
    materials: materials,
    genders: genders,
    types: types,
    //non ha lenghts perche la lunghezza sarebbe la taglia
    fits: fits,
    microCategory: ["basic", "palazzo", "zampa d'elefante"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "felpe",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: ["cappuccio", "zip", "senza cappuccio"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "giacche",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: [
      "leggere",
      "impermeabili",
      "smanicate",
      "vento",
      "sportive",
      "invernali",
      "piumini",
      "bomber",
      "jeans",
      "gilet",
    ],
    sizes: clothesSizes,
  },
  {
    macroCategory: "blazer",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: [
      "leggeri",
      "impermeabili",
      "smanicati",
      "vento",
      "sportivi",
      "invernali",
      "jeans",
    ],
    sizes: clothesSizes,
  },
  {
    macroCategory: "cappotti",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: ["basic", "parka", "trench", "invernali"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "maglioni",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    collars: sweaterCollars,
    microCategory: ["liscio", "trecce", "coste"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "costumi",
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: ["interi", "bikini", "bermuda", "boxer", "slip"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "gonne",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: ["pieghe", "trapezio", "tubino", "portafoglio", "jeans"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "shorts",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategory: ["basic", "sportivi"],
    sizes: clothesSizes,
  },
  {
    macroCategory: "scarpe",
    occasions: occasions,
    materials: materials,
    genders: genders,
    microCategory: [
      "sneakers",
      "sandali",
      "piatte",
      "ciabatte",
      "tacco",
      "ballerine",
      "stivaletti",
      "stivali",
      "sportive",
      "mare",
      "sposa",
      "pantofole",
      "trekking",
    ],
    sizes: shoesSizes,
  },
  {
    macroCategory: "polo",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategories: [
      "maniche lunghe",
      "maniche corte",
      "mezze maniche",
      "senza maniche",
    ],
    sizes: clothesSizes,
  },
  {
    macroCategory: "bermuda",
    occasions: occasions,
    materials: materials,
    genders: genders,
    lengths: lengths,
    types: types,
    fits: fits,
    microCategories: ["cargo", "jeans", "tuta", "basic"],
    sizes: clothesSizes,
  },
];
