export const brands = [
  "A fish named fred",
  "a&o FEEL THE LIFE",
  "A-LAB",
  "A-TRUE",
  "A.S.98",
  "a.soyi",
  "A.W.A.K.E. MODE",
  "Aaron Wallace",
  "Abbie and Rose",
  "Abercrombie & Fitch",
  "ABITIMA® CLINIC",
  "ABODI",
  "Abrand Jeans",
  "Abro",
  "Absolut Cashmere",
  "ABSOLUTE CULT",
  "Absolution",
  "AC&CO / ALTINYILDIZ CLASSICS",
  "AC/DC",
  "Acalee",
  "ACBC x Missoni",
  "ACCOJE",
  "Achel par Lemahieu",
  "Achelia",
  "ACHHA",
  "AchievePrime",
  "ACID",
  "Aclima",
  "Acqua di Parma",
  "Active by Zizzi",
  "ACTIVE X PAPRIKA",
  "Adamo",
  "Adax",
  "ADDITION Sustainable Apparel",
  "Adele Dejak",
  "Adelheid",
  "Adelia´s",
  "ADERERROR",
  "ADIA",
  "Adidas",
  "Adlysh",
  "ADOLFO DOMINGUEZ",
  "Adrianna Papell",
  "aerie",
  "AESPAREL",
  "AESTHER EKME",
  "AEVOR",
  "Afect",
  "Afends",
  "Affenzahn",
  "AFORAWORLD",
  "AFROZAN",
  "AFS Schuhe",
  "After Eden",
  "AG Jeans",
  "Agamaa",
  "Agent Nateur",
  "Agent Provocateur",
  "AGNELLE",
  "Agolde",
  "AGU",
  "AHAVA",
  "Áhkká",
  "Ahlvar Gallery",
  "AHORNZWEIG",
  "Aigle",
  "AIGNER",
  "Aimée.L",
  "AIRE",
  "Airinum",
  "Airpaq",
  "AjC",
  "AJLAJK",
  "Akitsune",
  "AKNVAS",
  "Aku",
  "Akuko",
  "Alassio",
  "ALBERT KREUZ",
  "Albert Schäfer",
  "Alberta Ferretti",
  "Alberto Fermani",
  "Alberto Guardiani",
  "ALBERTO Pants",
  "Alberto Zago",
  "Alcina",
  "ALDO",
  "Alejandra de Coss",
  "ALEKO",
  "Aleon",
  "alessandro",
  "Alessandro Salvarini",
  "Alessandro Zavetti",
  "ALESYA ORLÓVA",
  "Alexa Chung",
  "Alexander Cobb",
  "Alexander McQueen",
  "ALEXANDER SMITH",
  "Alexandra Moura",
  "Aleyolé",
  "Alginoo",
  "Alice + Olivia",
  "Alife",
  "alife & kickin",
  "ALIGNE",
  "Aline Celi",
  "all in",
  "ALL YOU NEAT.",
  "Allavola",
  "Allbirds",
  "ALLEGRINO",
  "Allen Edmonds",
  "Allies of Skin",
  "Allrounder",
  "AllSaints",
  "Allthemen",
  "Alma en Pena",
  "Almaazur",
  "Almgwand",
  "Almsach",
  "ALOHAS",
  "Alpacas",
  "Alpe",
  "Alpenfee",
  "Alpenflüstern",
  "Alpenglück",
  "Alpha Industries",
  "Alpina",
  "Alpine White",
  "Altra",
  "Alumaxx",
  "ALV by Alviero Martini",
  "Alvi",
  "Alviero Martini",
  "ALYICH",
  "Amaci&Sons",
  "AMANDA",
  "Amarossa",
  "Amato Daniele",
  "Amazfit",
  "Ambellis",
  "Amber & June",
  "AMBIANCE",
  "Ambitious",
  "Amblers Safety",
  "âme pure",
  "Amen",
  "America Today",
  "American College",
  "American Crew",
  "American Eagle",
  "American Tourister",
  "American Vintage",
  "AMISH",
  "AMMANN",
  "amor",
  "Amor, Trust & Truth",
  "AMORETTO MILANO",
  "Amsterdenim",
  "Amyline",
  "AN'GE",
  "Ana Alcazar",
  "ANAKI",
  "Anastasia Beverly Hills",
  "Anatomic & Co.",
  "Anaya with love",
  "Anbac Toys",
  "Anchor & Crew",
  "And Shine",
  "ANDAM",
  "Anderson's",
  "ANDIATA",
  "Andijamo",
  "Andrea Conti",
  "ANDREA IYAMAH",
  "Andres Machado",
  "Andrew James",
  "Anekke",
  "anello",
  "Anemoss",
  "Anerkjendt",
  "Angel & Rocket",
  "ÁNGEL ALARCÓN",
  "Angelico",
  "Angelika Józefczyk",
  "Angels",
  "Ania Haie",
  "Aniston",
  "Anita",
  "Ann Summers",
  "Anna Aura",
  "Anna Field",
  "Anna Kaval",
  "ANNA MONTANA",
  "ANNAMARIAANGELIKA",
  "Anne Klein",
  "Anne Semonin",
  "Anne-Marie Chagnon",
  "ANNEBRAUNER",
  "Anonymous Copenhagen",
  "Another A",
  "Another Influence",
  "Another-Label",
  "Antarctica Boots",
  "Antebies",
  "Anthoni Crown",
  "Anthony",
  "Antipodes",
  "Antoine et Lili",
  "Anton Heunis",
  "Antonio Moretto",
  "Antony Morato",
  "antura accessori",
  "Apart",
  "Apepazza",
  "APoem",
  "Apolina",
  "Apothecary by Dr. Botanicals",
  "Apple",
  "Apple of Eden",
  "Apple of my eye",
  "APRICOT",
  "Apricot",
  "April & Alex",
  "Apriori",
  "Apus",
  "Aqualung",
  "AQUIS",
  "ara",
  "Araa Active",
  "Aramis",
  "Aran Jewels",
  "Arapaima Fishing Equipment",
  "arbū",
  "Arc'teryx",
  "Archivio 22",
  "Arcopedico",
  "Arctic Seven",
  "Ardell",
  "areco",
  "Arena",
  "ARI ANWA Skincare",
  "Aries",
  "ARIZONA",
  "ARIZONA LOVE",
  "ARKET",
  "ARKK Copenhagen",
  "Arma",
  "Armada",
  "Armani Exchange",
  "ARMEDANGELS",
  "Armor lux",
  "Arnetta",
  "Arnette",
  "Arrivly",
  "Art Bella",
  "Arte Antwerp",
  "Artiker",
  "ARTLIFT",
  "Artsac",
  "Arus",
  "AS IF Clothing",
  "ASCOPERA",
  "Ascot",
  "ASÉT BOGATY",
  "Ash",
  "Ashley Brooke by heine",
  "ASICS",
  "ASICS SportStyle",
  "ASIS-TOBE",
  "ASOBU",
  "ASPESI",
  "ASPORTUGUESAS",
  "ASRA",
  "Assuili",
  "Aster",
  "Astra",
  "Astrid & Miyu",
  "Atelier Gardeur",
  "Atelier Rêve",
  "Atelier Torino",
  "Atella",
  "Athlecia",
  "Athleta",
  "Atina Cosmetics",
  "Atomic",
  "Attesa Maternity",
  "Attilio Giusti Leombruni",
  "Aubade",
  "aubi",
  "Auden Cavill",
  "Audley",
  "Auer",
  "August Berg",
  "August November",
  "Augustinus Bader",
  "Aunts & Uncles",
  "Aurélie Bidermann",
  "AUS WOOLI AUSTRALIA",
  "Australian",
  "Australian",
  "Autark",
  "Autry",
  "AVA",
  "Avant-Garde Paris",
  "AVE + EDAM",
  "Ave&You",
  "Aveda",
  "Avène",
  "Avengers",
  "Avenue",
  "AVOURE COUTURE",
  "Aware by Vero Moda",
  "Awesome Apparel",
  "Axelda",
  "Aygill's",
  "Aylashes",
  "Azro Silver",
  "Azzaro Parfums",
  "B FNKY",
  "B YOGA",
  "B'Chill",
  "b.belt",
  "B.Bros",
  "B.NOSY",
  "B.Tempt'd",
  "b.young",
  "BA&SH",
  "BA98",
  "Baagl",
  "Babolat",
  "BABOR",
  "BABOUCHE Lifestyle",
  "Baby Annabell",
  "Baby Born",
  "Baby Pattini",
  "Baby Shark",
  "Baby Sweets",
  "BABY-G",
  "BabyCosy Organic",
  "BABYKAJO",
  "BaByliss",
  "Back Bloom",
  "Back70",
  "Backtee",
  "Bad Again Paris",
  "BadeFee",
  "Badger",
  "BadRhino",
  "BADURA",
  "Bagatt",
  "Bahe",
  "Baie Botanique",
  "BAÏJA",
  "Bailey of Hollywood",
  "BAJO",
  "Bakaree",
  "Baker by Ted Baker",
  "Baldessarini",
  "Baldinini",
  "Baldowski",
  "BALI BODY",
  "Bali-BAli",
  "Balia",
  "BALL",
  "Ballerette",
  "Ballop",
  "Ballūta",
  "Bally",
  "Baloot",
  "Bama",
  "Bamar Nicol",
  "Bambocks",
  "Bamboo Basics",
  "Banana Moon",
  "Banana Republic",
  "Band of Rascals",
  "Baracuta",
  "Barbara Lebek",
  "Barber Pro",
  "Barberians",
  "Barbie",
  "Barbour",
  "bareMinerals",
  "Barrow",
  "Barts",
  "BASE LEVEL",
  "Basefield",
  "Basics and More",
  "Basics from Amsterdam",
  "Basler",
  "BASLER BY WALDLÄUFER",
  "Bassetti",
];
