version: "3.3"
services:
  project1_api:
    restart: always
    build: .
    ports:
      - "80:3000" #localhost => localhost:5000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
