version: "3.3"
services:
  nginx: #nginx
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      #- "27017:27017" linked to mongodb?
    depends_on:
      - api
  api:
    restart: always
    build: .
    ports:
      - "8000-8020:3000" #localhost => localhost:5000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 2
